---
title: "git_01"
author: "bryanbunch"
date: "9/7/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>
’Twas brillig, and the slithy toves   
Did gyre and gimble in the wabe:    
All mimsy were the borogoves,    
And the mome raths outgrabe.    
      
“Beware the Jabberwock, my son!    
The jaws that bite, the claws that catch!    
Beware the Jubjub bird, and shun    
The frumious Bandersnatch!”    

## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  

## Third Verse
<Put the first two verses of The Walrus and the Carpenter here>
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  

## Last Verse
<Put a short poem of your choice 8-20 lines,here>
Of course I'm fine, why do you ask?    
Oh don't mind this, it's just my mask.    
It hides the grief, it hides the strife,    
I wear this mask, to escape the knife.    

Don't forget this, my pain is real,    
I'm not lying, this is how I feel.    
You sit there saying, it can't be true,    
it is for me, just not for you.    

You say my heart, must be a sight,   
cold as ice, and black as night.    
It's not my heart, only my soul,    
but killing me, must be your goal.    

You're getting close, I hope you know,    
you really don't, have far to go.   
Soon enough, I'll reach my end,   
you'll have my soul, to tear and rend.   

But you don't know, you never ask,   
you never look, beyond the mask.   
The look on my face, is giving me away,   
I wonder now, what you will say?   


Source: http://www.familyfriendpoems.com/poem/just-my-mask
#FamilyFriendPoems